# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RAT' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'RealmSwift', '~> 2.5.0'
  pod 'SwiftyVK', :git => 'https://github.com/WE-St0r/SwiftyVK.git'
end
